global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'rack-controllers'
    static_configs:
      - targets:
          - 'rack-controller-0:8000'
          - 'rack-controller-1:8000'
          - 'rack-controller-2:8000'
          - 'rack-controller-3:8000'

  - job_name: 'dc-controller'
    static_configs:
      - targets:
          - 'dc-controller:8000'
