apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc-controller
  namespace: netwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dc-controller
  template:
    metadata:
      labels:
        app: dc-controller
    spec:
      containers:
        - name: dc-controller
          image: netwatch-dc-controller:local
          imagePullPolicy: Never
          ports:
            - containerPort: 9990
              protocol: TCP
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DC_ID
              value: "0"
            - name: TCP_LISTEN_PORT
              value: "9990"
            - name: NUM_RACKS
              value: "4"
            - name: METRICS_PORT
              value: "8000"
